"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { Plus, Trash2, Users, Mail, Phone, User, FileText, Sparkles, Send, Copy, Eye, Clock } from "lucide-react";

import { SiteHeader } from "@/components/site/site-header";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { NewsletterPreview } from "@/components/newsletter-preview";

interface NewsletterSubscriber {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  phoneNumber: string;
  subscribedAt: string;
  status: "active" | "unsubscribed";
}

// Sample data
const defaultSubscribers: NewsletterSubscriber[] = [
  {
    id: "1",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "+852 9123 4567",
    subscribedAt: "2026-07-15T10:30:00Z",
    status: "active",
  },
  {
    id: "2",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    phoneNumber: "+852 9876 5432",
    subscribedAt: "2026-07-20T14:45:00Z",
    status: "active",
  },
  {
    id: "3",
    firstName: "Michael",
    lastName: "Wong",
    email: "michael.wong@example.com",
    phoneNumber: "+852 8765 4321",
    subscribedAt: "2026-07-25T09:15:00Z",
    status: "active",
  },
];

function loadSubscribers(): NewsletterSubscriber[] {
  if (typeof window === "undefined") return defaultSubscribers;
  const stored = localStorage.getItem("love21_newsletter");
  if (stored) {
    try {
      const parsed: unknown[] = JSON.parse(stored);
      return parsed.map((item: any) => ({
        id: item.id || Date.now().toString(),
        firstName: item.firstName || "",
        lastName: item.lastName || "",
        email: item.email || "",
        phoneNumber: item.phoneNumber || "",
        subscribedAt: item.subscribedAt || new Date().toISOString(),
        status: item.status === "unsubscribed" ? "unsubscribed" : "active",
      })) as NewsletterSubscriber[];
    } catch {
      return defaultSubscribers;
    }
  }
  return defaultSubscribers;
}

function saveSubscribers(subscribers: NewsletterSubscriber[]): void {
  if (typeof window !== "undefined") {
    localStorage.setItem("love21_newsletter", JSON.stringify(subscribers));
  }
}

// Clean AI messages from the output
function cleanAIMessages(content: string): string {
  // Remove common AI introductory phrases
  const patterns = [
    /^.*?(I have all the real content|Here is your email-ready newsletter|Note:|I'll generate|Let me|Here's|I've created|The newsletter|I can produce|If you want|I will|Let me know|You can find|Check out|Don't forget|I've included|Feel free|Please let me know|Would you like).*$/gim,
    /^---*$/gm,
    /^>.*$/gm,
    /^© 2026.*$/gm,
    /^\*.*\*$/gm,
    /^Generated by.*$/gm,
    /^AI.*$/gm,
  ];

  let cleaned = content;
  for (const pattern of patterns) {
    cleaned = cleaned.replace(pattern, '');
  }

  // Remove extra blank lines
  cleaned = cleaned.split('\n').filter(line => line.trim() !== '').join('\n');

  return cleaned.trim();
}

// Format newsletter content - remove markdown and clean up
function formatNewsletterContent(content: string): string {
  let formatted = content
    // Remove markdown bold
    .replace(/\*\*(.*?)\*\*/g, '$1')
    // Remove markdown italics
    .replace(/\*(.*?)\*/g, '$1')
    // Remove horizontal lines
    .replace(/---/g, '')
    // Remove heading markers
    .replace(/#{1,6}\s/g, '')
    // Replace * with bullet points
    .replace(/\*/g, '•')
    // Clean up multiple spaces
    .replace(/  +/g, ' ')
    // Add proper spacing between sections
    .split('\n')
    .filter(line => line.trim() !== '')
    .join('\n\n');

  return formatted.trim();
}

export default function AdminNewsletterPage() {
  // ---- Existing subscriber management states ----
  const [subscribers, setSubscribers] = useState<NewsletterSubscriber[]>([]);
  const [editingSubscriber, setEditingSubscriber] = useState<NewsletterSubscriber | null>(null);
  const [formData, setFormData] = useState({
    firstName: "",
    lastName: "",
    email: "",
    phoneNumber: "",
  });
  const [searchTerm, setSearchTerm] = useState("");

  // ---- AI Newsletter states ----
  const [prompt, setPrompt] = useState(
    `Generate a polished, professional newsletter for Love 21 Foundation using ONLY content from their official website (love21foundation.com).

Format the newsletter with:
- A compelling subject line
- A warm greeting
- Program highlights (Sports, Nutrition, Family, CSR)
- Events section (Beyond Limits Banquet, Charity Raffle)
- Impact stats
- A call to action

Use proper paragraphs, no markdown symbols like ** or ---. Make it look like a professional email newsletter ready to send.`
  );
  const [generatedContent, setGeneratedContent] = useState('');
  const [subject, setSubject] = useState('Love 21 Foundation Newsletter');
  const [loading, setLoading] = useState(false);
  const [sending, setSending] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [showPreview, setShowPreview] = useState(false);
  const [elapsedTime, setElapsedTime] = useState(0);
  const [isGenerating, setIsGenerating] = useState(false);

  // ---- Load subscribers on mount ----
  useEffect(() => {
    setSubscribers(loadSubscribers());
  }, []);

  // ---- Timer for generation ----
  useEffect(() => {
    let interval: NodeJS.Timeout;
    if (isGenerating) {
      setElapsedTime(0);
      interval = setInterval(() => {
        setElapsedTime(prev => prev + 1);
      }, 1000);
    }
    return () => clearInterval(interval);
  }, [isGenerating]);

  // ---- Existing: Subscriber CRUD ----
  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();
    let newSubscribers = [...subscribers];
    if (editingSubscriber) {
      const index = newSubscribers.findIndex((sub) => sub.id === editingSubscriber.id);
      if (index !== -1) {
        newSubscribers[index] = {
          ...newSubscribers[index],
          firstName: formData.firstName,
          lastName: formData.lastName,
          email: formData.email,
          phoneNumber: formData.phoneNumber,
        };
      }
      setEditingSubscriber(null);
    } else {
      const newSubscriber: NewsletterSubscriber = {
        id: Date.now().toString(),
        firstName: formData.firstName,
        lastName: formData.lastName,
        email: formData.email,
        phoneNumber: formData.phoneNumber,
        subscribedAt: new Date().toISOString(),
        status: "active",
      };
      newSubscribers = [newSubscriber, ...newSubscribers];
    }
    setSubscribers(newSubscribers);
    saveSubscribers(newSubscribers);
    resetForm();
  };

  const resetForm = () => {
    setFormData({
      firstName: "",
      lastName: "",
      email: "",
      phoneNumber: "",
    });
    setEditingSubscriber(null);
  };

  const deleteSubscriber = (id: string) => {
    const newSubscribers = subscribers.filter((sub) => sub.id !== id);
    setSubscribers(newSubscribers);
    saveSubscribers(newSubscribers);
  };

  const toggleStatus = (id: string) => {
    const newSubscribers: NewsletterSubscriber[] = subscribers.map((sub) =>
      sub.id === id
        ? { ...sub, status: sub.status === "active" ? "unsubscribed" : "active" }
        : sub
    );
    setSubscribers(newSubscribers);
    saveSubscribers(newSubscribers);
  };

  const editSubscriber = (subscriber: NewsletterSubscriber) => {
    setEditingSubscriber(subscriber);
    setFormData({
      firstName: subscriber.firstName,
      lastName: subscriber.lastName,
      email: subscriber.email,
      phoneNumber: subscriber.phoneNumber,
    });
  };

  const filteredSubscribers = subscribers.filter(
    (sub) =>
      sub.firstName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      sub.lastName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      sub.email.toLowerCase().includes(searchTerm.toLowerCase()) ||
      sub.phoneNumber.includes(searchTerm)
  );

  const activeCount = subscribers.filter((sub) => sub.status === "active").length;
  const totalSubscribers = subscribers.length;

  // ---- AI Newsletter Functions ----
  const generateNewsletter = async () => {
    setLoading(true);
    setIsGenerating(true);
    setError('');
    setGeneratedContent('');
    setSuccess('');
    setElapsedTime(0);

    try {
      const response = await fetch('/api/newsletter', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt }),
      });

      const data = await response.json();

      if (data.success) {
        // Clean AI messages first
        const cleanedContent = cleanAIMessages(data.content);
        const formattedContent = formatNewsletterContent(cleanedContent);
        setGeneratedContent(formattedContent);
        // Auto-extract subject from content
        const subjectMatch = data.content.match(/Subject:?\s*(.*?)(?:\n|$)/i);
        if (subjectMatch) {
          setSubject(subjectMatch[1].trim());
        }
        setSuccess('Newsletter generated successfully!');
      } else {
        setError(data.error || 'Failed to generate newsletter');
      }
    } catch (err) {
      setError('Failed to connect to the newsletter service. Please try again.');
      console.error(err);
    } finally {
      setLoading(false);
      setIsGenerating(false);
    }
  };

  const sendNewsletter = async () => {
    if (!generatedContent) {
      setError('No newsletter content to send. Generate a newsletter first.');
      return;
    }

    if (!subject) {
      setError('Please enter a subject line.');
      return;
    }

    const activeSubscribers = subscribers.filter((s) => s.status === 'active');
    if (activeSubscribers.length === 0) {
      setError('No active subscribers to send to.');
      return;
    }

    setSending(true);
    setError('');
    setSuccess('');

    try {
      const response = await fetch('/api/send-newsletter', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          subject,
          content: generatedContent,
        }),
      });

      const data = await response.json();

      if (data.success) {
        setSuccess(data.message || `Newsletter sent to ${activeSubscribers.length} subscribers!`);
      } else {
        setError(data.error || 'Failed to send newsletter');
      }
    } catch (err) {
      setError('Failed to send newsletter');
      console.error(err);
    } finally {
      setSending(false);
    }
  };

  // Format time display
  const formatTime = (seconds: number): string => {
    if (seconds < 60) {
      return `${seconds}s`;
    }
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    if (secs === 0) {
      return `${mins}m`;
    }
    return `${mins}m ${secs}s`;
  };

  return (
    <>
      <SiteHeader />
      <main className="min-h-screen px-4 py-8 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-6xl">
          <div className="mb-6 flex items-center justify-between">
            <div>
              <h1 className="text-3xl font-bold tracking-tight">Newsletter Management</h1>
              <p className="mt-1 text-sm text-muted-foreground">
                Manage subscribers and generate AI-powered newsletters
              </p>
            </div>
            <Link
              href="/admin"
              className="text-sm text-[#d4a373] hover:underline flex items-center gap-1"
            >
              ← Back to Admin
            </Link>
          </div>

          {/* Stats */}
          <div className="mb-6 grid gap-4 sm:grid-cols-4">
            <Card>
              <CardContent className="pt-6">
                <div className="flex items-center gap-4">
                  <div className="rounded-full bg-blue-100 p-3 text-blue-600">
                    <Users className="h-5 w-5" />
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground">Total Subscribers</p>
                    <p className="text-2xl font-bold">{totalSubscribers}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="pt-6">
                <div className="flex items-center gap-4">
                  <div className="rounded-full bg-green-100 p-3 text-green-600">
                    <Mail className="h-5 w-5" />
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground">Active</p>
                    <p className="text-2xl font-bold">{activeCount}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="pt-6">
                <div className="flex items-center gap-4">
                  <div className="rounded-full bg-purple-100 p-3 text-purple-600">
                    <FileText className="h-5 w-5" />
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground">Unsubscribed</p>
                    <p className="text-2xl font-bold">{totalSubscribers - activeCount}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="pt-6">
                <div className="flex items-center gap-4">
                  <div className="rounded-full bg-pink-100 p-3 text-pink-600">
                    <Sparkles className="h-5 w-5" />
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground">AI Generated</p>
                    <p className="text-2xl font-bold">{generatedContent ? '✅' : '⏳'}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* ============================================================ */}
          {/* SECTION 1: AI NEWSLETTER GENERATOR */}
          {/* ============================================================ */}
          <Card className="mb-8 border-2 border-[#d4a373]/30">
            <CardHeader className="bg-[#d4a373]/5">
              <div className="flex items-center gap-2">
                <Sparkles className="h-5 w-5 text-[#d4a373]" />
                <CardTitle>AI Newsletter Generator</CardTitle>
                <CardDescription className="ml-2">
                  Generate a polished newsletter using AI from Love 21's website content
                </CardDescription>
              </div>
            </CardHeader>
            <CardContent className="pt-6">
              <div className="space-y-4">
                {/* Prompt Box - Increased Size */}
                <div>
                  <Label htmlFor="prompt">Prompt</Label>
                  <textarea
                    id="prompt"
                    value={prompt}
                    onChange={(e) => setPrompt(e.target.value)}
                    className="mt-1 w-full rounded-lg border p-3 min-h-[200px] text-sm"
                  />
                </div>

                <div className="flex flex-wrap items-center gap-3">
                  <Button
                    onClick={generateNewsletter}
                    disabled={loading}
                    className="bg-[#d4a373] hover:bg-[#c08f5c]"
                  >
                    {loading ? 'Generating...' : 'Generate Newsletter'}
                  </Button>

                  {isGenerating && (
                    <div className="flex items-center gap-2 text-sm text-muted-foreground">
                      <Clock className="h-4 w-4 animate-pulse" />
                      <span>Generating... {formatTime(elapsedTime)} (may take 1-2 mins)</span>
                    </div>
                  )}

                  {generatedContent && !loading && (
                    <div className="flex flex-wrap gap-2">
                      <Button
                        variant="outline"
                        onClick={() => setShowPreview(!showPreview)}
                        className="flex items-center gap-2"
                      >
                        <Eye className="h-4 w-4" />
                        {showPreview ? 'Hide Preview' : 'Show Preview'}
                      </Button>
                      <Button
                        variant="outline"
                        onClick={() => {
                          navigator.clipboard.writeText(generatedContent);
                          setSuccess('Copied to clipboard!');
                          setTimeout(() => setSuccess(''), 3000);
                        }}
                        className="flex items-center gap-2"
                      >
                        <Copy className="h-4 w-4" />
                        Copy
                      </Button>
                    </div>
                  )}
                </div>

                {loading && (
                  <div className="rounded-lg border border-blue-200 bg-blue-50 p-4 text-sm text-blue-700">
                    <div className="flex items-center gap-2">
                      <div className="h-4 w-4 animate-spin rounded-full border-2 border-blue-600 border-t-transparent"></div>
                      <span>This may take 1-2 minutes. Please wait...</span>
                    </div>
                  </div>
                )}

                {error && (
                  <div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">
                    {error}
                  </div>
                )}

                {success && (
                  <div className="rounded-lg border border-green-200 bg-green-50 p-3 text-sm text-green-700">
                    {success}
                  </div>
                )}

                {generatedContent && (
                  <div className="mt-4 space-y-4 border-t pt-4">
                    <div>
                      <Label htmlFor="subject">Subject Line</Label>
                      <Input
                        id="subject"
                        value={subject}
                        onChange={(e) => setSubject(e.target.value)}
                        className="mt-1"
                      />
                    </div>

                    {/* Preview Section - Shows HTML preview */}
                    {showPreview && (
                      <div>
                        <div className="flex items-center justify-between mb-2">
                          <Label>Preview (HTML)</Label>
                        </div>
                        <div className="max-h-[600px] overflow-auto rounded-lg border bg-gray-50 p-6">
                          <NewsletterPreview content={generatedContent} />
                        </div>
                      </div>
                    )}

                    {/* Text Output - Changed from "Raw Content" to "Text Output" */}
                    <div>
                      <div className="flex items-center justify-between mb-2">
                        <Label>Text Output</Label>
                        {!showPreview && (
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => setShowPreview(true)}
                            className="text-[#d4a373] hover:text-[#c08f5c]"
                          >
                            <Eye className="h-3 w-3 mr-1" />
                            Show Preview
                          </Button>
                        )}
                      </div>
                      <div className="max-h-[300px] overflow-auto rounded-lg border p-4 whitespace-pre-wrap bg-white text-sm">
                        {generatedContent}
                      </div>
                    </div>

                    <div className="flex flex-wrap gap-2">
                      <Button
                        onClick={sendNewsletter}
                        disabled={sending || activeCount === 0}
                        className="bg-green-600 hover:bg-green-700 flex items-center gap-2"
                      >
                        <Send className="h-4 w-4" />
                        {sending ? 'Sending...' : `Send to ${activeCount} Subscribers`}
                      </Button>
                      <Button
                        variant="outline"
                        onClick={() => {
                          setGeneratedContent('');
                          setSubject('Love 21 Foundation Newsletter');
                          setSuccess('');
                          setShowPreview(false);
                        }}
                        className="text-red-600"
                      >
                        Discard
                      </Button>
                    </div>
                    {activeCount === 0 && (
                      <p className="text-sm text-amber-600">
                        ⚠️ No active subscribers to send to. Add subscribers below.
                      </p>
                    )}
                  </div>
                )}
              </div>
            </CardContent>
          </Card>

          {/* ============================================================ */}
          {/* SECTION 2: SUBSCRIBER MANAGEMENT (Existing Features) */}
          {/* ============================================================ */}

          {/* Add Subscriber Form */}
          <Card className="mb-8">
            <CardHeader>
              <CardTitle>{editingSubscriber ? "Edit Subscriber" : "Add New Subscriber"}</CardTitle>
              <CardDescription>
                {editingSubscriber
                  ? "Update the subscriber's contact information"
                  : "Add a new subscriber to the newsletter list"}
              </CardDescription>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleSubmit} className="space-y-4">
                <div className="grid gap-4 sm:grid-cols-2">
                  <div className="space-y-2">
                    <Label htmlFor="firstName">
                      <span className="flex items-center gap-1">
                        <User className="h-3 w-3" /> First Name
                      </span>
                    </Label>
                    <Input
                      id="firstName"
                      value={formData.firstName}
                      onChange={(e) => setFormData({ ...formData, firstName: e.target.value })}
                      required
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="lastName">
                      <span className="flex items-center gap-1">
                        <User className="h-3 w-3" /> Last Name
                      </span>
                    </Label>
                    <Input
                      id="lastName"
                      value={formData.lastName}
                      onChange={(e) => setFormData({ ...formData, lastName: e.target.value })}
                      required
                    />
                  </div>
                </div>
                <div className="grid gap-4 sm:grid-cols-2">
                  <div className="space-y-2">
                    <Label htmlFor="email">
                      <span className="flex items-center gap-1">
                        <Mail className="h-3 w-3" /> Email Address <span className="text-red-500">*</span>
                      </span>
                    </Label>
                    <Input
                      id="email"
                      type="email"
                      value={formData.email}
                      onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                      placeholder="email@example.com"
                      required
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="phoneNumber">
                      <span className="flex items-center gap-1">
                        <Phone className="h-3 w-3" /> Phone Number
                      </span>
                    </Label>
                    <Input
                      id="phoneNumber"
                      value={formData.phoneNumber}
                      onChange={(e) => setFormData({ ...formData, phoneNumber: e.target.value })}
                      placeholder="+852 9123 4567"
                    />
                  </div>
                </div>
                <div className="flex gap-2">
                  <Button type="submit">
                    <Plus className="mr-2 h-4 w-4" />
                    {editingSubscriber ? "Update Subscriber" : "Add Subscriber"}
                  </Button>
                  {editingSubscriber && (
                    <Button type="button" variant="outline" onClick={resetForm}>
                      Cancel
                    </Button>
                  )}
                </div>
              </form>
            </CardContent>
          </Card>

          {/* Subscriber List */}
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <h2 className="text-lg font-semibold">Subscribers List</h2>
              <div className="flex items-center gap-3">
                <Input
                  placeholder="Search subscribers..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="w-56 text-sm"
                />
              </div>
            </div>

            <Card>
              <CardContent className="p-0">
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead className="bg-muted/50">
                      <tr className="border-b">
                        <th className="h-12 px-4 text-left font-medium text-muted-foreground w-[100px]">Status</th>
                        <th className="h-12 px-4 text-left font-medium text-muted-foreground">First Name</th>
                        <th className="h-12 px-4 text-left font-medium text-muted-foreground">Last Name</th>
                        <th className="h-12 px-4 text-left font-medium text-muted-foreground">Email</th>
                        <th className="h-12 px-4 text-left font-medium text-muted-foreground">Phone</th>
                        <th className="h-12 px-4 text-center font-medium text-muted-foreground">Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                      {filteredSubscribers.length === 0 ? (
                        <tr>
                          <td colSpan={6} className="py-8 text-center text-muted-foreground">
                            {searchTerm ? "No subscribers match your search" : "No subscribers yet. Add your first subscriber above."}
                          </td>
                        </tr>
                      ) : (
                        filteredSubscribers.map((subscriber) => (
                          <tr key={subscriber.id} className="border-b transition-colors hover:bg-muted/50">
                            <td className="p-4">
                              <button
                                onClick={() => toggleStatus(subscriber.id)}
                                className={`text-xs px-2 py-0.5 rounded-full cursor-pointer ${
                                  subscriber.status === "active"
                                    ? "bg-green-100 text-green-700 hover:bg-green-200"
                                    : "bg-gray-100 text-gray-500 hover:bg-gray-200"
                                }`}
                              >
                                {subscriber.status === "active" ? "Active" : "Unsubscribed"}
                              </button>
                            </td>
                            <td className="p-4 font-medium">{subscriber.firstName}</td>
                            <td className="p-4">{subscriber.lastName}</td>
                            <td className="p-4">
                              <a href={`mailto:${subscriber.email}`} className="text-[#d4a373] hover:underline">
                                {subscriber.email}
                              </a>
                            </td>
                            <td className="p-4">{subscriber.phoneNumber}</td>
                            <td className="p-4">
                              <div className="flex items-center justify-center gap-2">
                                <Button variant="outline" size="sm" onClick={() => editSubscriber(subscriber)}>
                                  Edit
                                </Button>
                                <Button variant="destructive" size="sm" onClick={() => deleteSubscriber(subscriber.id)}>
                                  <Trash2 className="h-3 w-3" />
                                </Button>
                              </div>
                            </td>
                          </tr>
                        ))
                      )}
                    </tbody>
                  </table>
                </div>
              </CardContent>
            </Card>
            <p className="text-xs text-muted-foreground">
              Showing {filteredSubscribers.length} of {totalSubscribers} subscribers
            </p>
          </div>
        </div>
      </main>
    </>
  );
}