"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { Plus, Trash2, Users, Mail, User, FileText, Sparkles, Send, Copy, Eye, Clock, History } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { NewsletterPreview } from "@/components/newsletter-preview";
import { api, NewsletterDelivery, NewsletterSubscriber } from "@/lib/api";

function cleanAIMessages(content: string): string {
  const patterns = [
    /^.*?(I have all the real content|Here is your email-ready newsletter|Note:|I'll generate|Let me|Here's|I've created|The newsletter|I can produce|If you want|I will|Let me know|You can find|Check out|Don't forget|I've included|Feel free|Please let me know|Would you like).*$/gim,
    /^---*$/gm,
    /^>.*$/gm,
    /^© 2026.*$/gm,
    /^\*.*\*$/gm,
    /^Generated by.*$/gm,
    /^AI.*$/gm,
  ];
  let cleaned = content;
  for (const pattern of patterns) cleaned = cleaned.replace(pattern, "");
  return cleaned.split("\n").filter((line) => line.trim() !== "").join("\n").trim();
}

function formatNewsletterContent(content: string): string {
  return content
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/---/g, "")
    .replace(/#{1,6}\s/g, "")
    .replace(/\*/g, "•")
    .replace(/  +/g, " ")
    .split("\n")
    .filter((line) => line.trim() !== "")
    .join("\n\n")
    .trim();
}

export default function AdminNewsletterPage() {
  const [subscribers, setSubscribers] = useState<NewsletterSubscriber[]>([]);
  const [deliveries, setDeliveries] = useState<NewsletterDelivery[]>([]);
  const [editingSubscriber, setEditingSubscriber] = useState<NewsletterSubscriber | null>(null);
  const [formData, setFormData] = useState({ firstName: "", lastName: "", email: "", phoneNumber: "" });
  const [searchTerm, setSearchTerm] = useState("");
  const [prompt, setPrompt] = useState(
    "Generate a polished newsletter for Love 21 Foundation with programme highlights, events, impact stats, and a call to action.",
  );
  const [generatedContent, setGeneratedContent] = useState("");
  const [subject, setSubject] = useState("Love 21 Foundation Newsletter");
  const [loading, setLoading] = useState(false);
  const [sending, setSending] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [showPreview, setShowPreview] = useState(false);

  async function loadData() {
    try {
      const [subscriberList, deliveryList] = await Promise.all([
        api.listNewsletterSubscribers(),
        api.listNewsletterDeliveries(),
      ]);
      setSubscribers(subscriberList);
      setDeliveries(deliveryList);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not load newsletter data");
    }
  }

  useEffect(() => {
    loadData();
  }, []);

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setError("");
    try {
      if (editingSubscriber) {
        await api.updateNewsletterSubscriber(editingSubscriber.id, {
          first_name: formData.firstName,
          last_name: formData.lastName,
          email: formData.email,
          phone_number: formData.phoneNumber || null,
        });
      } else {
        await api.createNewsletterSubscriber({
          first_name: formData.firstName,
          last_name: formData.lastName,
          email: formData.email,
          phone_number: formData.phoneNumber || null,
          status: "active",
        });
      }
      await loadData();
      resetForm();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not save subscriber");
    }
  };

  const resetForm = () => {
    setFormData({ firstName: "", lastName: "", email: "", phoneNumber: "" });
    setEditingSubscriber(null);
  };

  const deleteSubscriber = async (id: number) => {
    await api.deleteNewsletterSubscriber(id);
    await loadData();
  };

  const toggleStatus = async (subscriber: NewsletterSubscriber) => {
    await api.updateNewsletterSubscriber(subscriber.id, {
      status: subscriber.status === "active" ? "unsubscribed" : "active",
    });
    await loadData();
  };

  const filteredSubscribers = subscribers.filter(
    (sub) =>
      sub.first_name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      sub.last_name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      sub.email.toLowerCase().includes(searchTerm.toLowerCase()) ||
      (sub.phone_number ?? "").includes(searchTerm),
  );

  const activeCount = subscribers.filter((sub) => sub.status === "active").length;

  const generateNewsletter = async () => {
    setLoading(true);
    setError("");
    setSuccess("");
    try {
      const response = await fetch("/api/newsletter", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt }),
      });
      const data = await response.json();
      if (data.success) {
        const formatted = formatNewsletterContent(cleanAIMessages(data.content));
        setGeneratedContent(formatted);
        const subjectMatch = data.content.match(/Subject:?\s*(.*?)(?:\n|$)/i);
        if (subjectMatch) setSubject(subjectMatch[1].trim());
        setSuccess("Newsletter generated successfully!");
      } else {
        setError(data.error || "Failed to generate newsletter");
      }
    } catch {
      setError("Failed to connect to the newsletter service.");
    } finally {
      setLoading(false);
    }
  };

  const sendNewsletter = async () => {
    if (!generatedContent || !subject) {
      setError("Generate content and set a subject before sending.");
      return;
    }
    setSending(true);
    setError("");
    try {
      const result = await api.sendNewsletter({ subject, content: generatedContent });
      setSuccess(result.message);
      await loadData();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to send newsletter");
    } finally {
      setSending(false);
    }
  };

  return (
    <main className="min-h-screen px-4 py-8 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-6xl">
        <div className="mb-6 flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Newsletter Management</h1>
            <p className="mt-1 text-sm text-muted-foreground">Manage subscribers, send campaigns, and review delivery history</p>
          </div>
          <Link href="/admin" className="text-sm text-[#d4a373] hover:underline">← Back to Admin</Link>
        </div>

        {error ? <p className="mb-4 rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</p> : null}
        {success ? <p className="mb-4 rounded-md bg-green-50 p-3 text-sm text-green-700">{success}</p> : null}

        <div className="mb-6 grid gap-4 sm:grid-cols-4">
          <Card><CardContent className="pt-6"><p className="text-sm text-muted-foreground">Total</p><p className="text-2xl font-bold">{subscribers.length}</p></CardContent></Card>
          <Card><CardContent className="pt-6"><p className="text-sm text-muted-foreground">Active</p><p className="text-2xl font-bold">{activeCount}</p></CardContent></Card>
          <Card><CardContent className="pt-6"><p className="text-sm text-muted-foreground">Campaigns sent</p><p className="text-2xl font-bold">{deliveries.length}</p></CardContent></Card>
          <Card><CardContent className="pt-6"><p className="text-sm text-muted-foreground">AI draft</p><p className="text-2xl font-bold">{generatedContent ? "Ready" : "—"}</p></CardContent></Card>
        </div>

        <Card className="mb-8 border-2 border-[#d4a373]/30">
          <CardHeader className="bg-[#d4a373]/5">
            <div className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-[#d4a373]" />
              <CardTitle>AI Newsletter Generator</CardTitle>
            </div>
            <CardDescription>Generated content is wrapped in the shared Love 21 HTML email template when sent.</CardDescription>
          </CardHeader>
          <CardContent className="pt-6 space-y-4">
            <textarea value={prompt} onChange={(e) => setPrompt(e.target.value)} className="w-full rounded-lg border p-3 min-h-[160px] text-sm" />
            <div className="flex flex-wrap gap-2">
              <Button onClick={generateNewsletter} disabled={loading} className="bg-[#d4a373] hover:bg-[#c08f5c]">
                {loading ? "Generating..." : "Generate Newsletter"}
              </Button>
              {generatedContent ? (
                <>
                  <Button variant="outline" onClick={() => setShowPreview(!showPreview)}><Eye className="mr-2 h-4 w-4" />Preview</Button>
                  <Button variant="outline" onClick={() => navigator.clipboard.writeText(generatedContent)}><Copy className="mr-2 h-4 w-4" />Copy</Button>
                </>
              ) : null}
            </div>
            {generatedContent ? (
              <div className="space-y-4 border-t pt-4">
                <div>
                  <Label htmlFor="subject">Subject Line</Label>
                  <Input id="subject" value={subject} onChange={(e) => setSubject(e.target.value)} className="mt-1" />
                </div>
                {showPreview ? <NewsletterPreview subject={subject} content={generatedContent} /> : null}
                <div className="max-h-[240px] overflow-auto rounded-lg border p-4 whitespace-pre-wrap bg-white text-sm">{generatedContent}</div>
                <Button onClick={sendNewsletter} disabled={sending || activeCount === 0} className="bg-green-600 hover:bg-green-700">
                  <Send className="mr-2 h-4 w-4" />
                  {sending ? "Sending..." : `Send to ${activeCount} subscribers`}
                </Button>
              </div>
            ) : null}
          </CardContent>
        </Card>

        <Card className="mb-8">
          <CardHeader>
            <CardTitle className="flex items-center gap-2"><History className="h-5 w-5" />Delivery history</CardTitle>
          </CardHeader>
          <CardContent>
            {deliveries.length === 0 ? (
              <p className="text-sm text-muted-foreground">No campaigns sent yet.</p>
            ) : (
              <ul className="space-y-3">
                {deliveries.map((delivery) => (
                  <li key={delivery.id} className="rounded-lg border p-4 text-sm">
                    <p className="font-semibold">{delivery.subject}</p>
                    <p className="text-muted-foreground">{delivery.recipient_count} recipients · {new Date(delivery.sent_at).toLocaleString()}</p>
                  </li>
                ))}
              </ul>
            )}
          </CardContent>
        </Card>

        <Card className="mb-8">
          <CardHeader>
            <CardTitle>{editingSubscriber ? "Edit Subscriber" : "Add Subscriber"}</CardTitle>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="grid gap-4 sm:grid-cols-2">
                <Input placeholder="First name" value={formData.firstName} onChange={(e) => setFormData({ ...formData, firstName: e.target.value })} required />
                <Input placeholder="Last name" value={formData.lastName} onChange={(e) => setFormData({ ...formData, lastName: e.target.value })} required />
              </div>
              <div className="grid gap-4 sm:grid-cols-2">
                <Input type="email" placeholder="Email" value={formData.email} onChange={(e) => setFormData({ ...formData, email: e.target.value })} required />
                <Input placeholder="Phone" value={formData.phoneNumber} onChange={(e) => setFormData({ ...formData, phoneNumber: e.target.value })} />
              </div>
              <Button type="submit"><Plus className="mr-2 h-4 w-4" />{editingSubscriber ? "Update" : "Add"}</Button>
            </form>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2"><Users className="h-5 w-5" />Subscribers</CardTitle>
            <Input placeholder="Search..." value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} className="max-w-xs" />
          </CardHeader>
          <CardContent className="space-y-2">
            {filteredSubscribers.map((subscriber) => (
              <div key={subscriber.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border p-3 text-sm">
                <div>
                  <p className="font-medium">{subscriber.first_name} {subscriber.last_name}</p>
                  <p className="text-muted-foreground">{subscriber.email}</p>
                </div>
                <div className="flex gap-2">
                  <Button variant="outline" size="sm" onClick={() => toggleStatus(subscriber)}>{subscriber.status}</Button>
                  <Button variant="outline" size="sm" onClick={() => { setEditingSubscriber(subscriber); setFormData({ firstName: subscriber.first_name, lastName: subscriber.last_name, email: subscriber.email, phoneNumber: subscriber.phone_number ?? "" }); }}>
                    <User className="h-3 w-3" />
                  </Button>
                  <Button variant="destructive" size="sm" onClick={() => deleteSubscriber(subscriber.id)}><Trash2 className="h-3 w-3" /></Button>
                </div>
              </div>
            ))}
          </CardContent>
        </Card>
      </div>
    </main>
  );
}
