"""initial schema

Revision ID: 7a473101a3c3
Revises: 
Create Date: 2026-08-01 09:26:16.647050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a473101a3c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('registrations', sa.Integer(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('fundraising', 'community', 'sports', 'nutrition', 'family', name='eventcategory'), nullable=False),
    sa.Column('status', sa.Enum('upcoming', 'ongoing', 'completed', name='eventstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_events_id'), 'admin_events', ['id'], unique=False)
    op.create_table('admin_volunteer_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('sport', 'nutrition', 'family', 'csr', name='programcategory'), nullable=False),
    sa.Column('schedule', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('filled', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closing', 'filled', name='programstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_volunteer_programs_id'), 'admin_volunteer_programs', ['id'], unique=False)
    op.create_table('analytics_daily_rollups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rollup_date', sa.Date(), nullable=False),
    sa.Column('metric_key', sa.String(length=120), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rollup_date', 'metric_key', name='uq_rollup_date_metric')
    )
    op.create_index(op.f('ix_analytics_daily_rollups_metric_key'), 'analytics_daily_rollups', ['metric_key'], unique=False)
    op.create_index(op.f('ix_analytics_daily_rollups_rollup_date'), 'analytics_daily_rollups', ['rollup_date'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_name', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=True),
    sa.Column('page_path', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_event_name'), 'analytics_events', ['event_name'], unique=False)
    op.create_index(op.f('ix_analytics_events_id'), 'analytics_events', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_events_occurred_at'), 'analytics_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_analytics_events_session_id'), 'analytics_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_table('newsletter_subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('active', 'unsubscribed', name='subscriberstatus'), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_subscribers_email'), 'newsletter_subscribers', ['email'], unique=True)
    op.create_index(op.f('ix_newsletter_subscribers_id'), 'newsletter_subscribers', ['id'], unique=False)
    op.create_table('support_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('impact_statement', sa.Text(), nullable=False),
    sa.Column('target_amount_hkd', sa.Integer(), nullable=False),
    sa.Column('funded_amount_hkd', sa.Integer(), nullable=False),
    sa.Column('moonclerk_url', sa.String(length=500), nullable=True),
    sa.Column('purchase_url', sa.String(length=500), nullable=True),
    sa.Column('quantity_needed', sa.Integer(), nullable=True),
    sa.Column('quantity_secured', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_opportunities_id'), 'support_opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_support_opportunities_kind'), 'support_opportunities', ['kind'], unique=False)
    op.create_index(op.f('ix_support_opportunities_slug'), 'support_opportunities', ['slug'], unique=True)
    op.create_index(op.f('ix_support_opportunities_status'), 'support_opportunities', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('donor', 'volunteer', 'member', 'admin', name='role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('volunteer_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('schedule_label', sa.String(length=120), nullable=False),
    sa.Column('location_label', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('filled_count', sa.Integer(), nullable=True),
    sa.Column('total_spots', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('cta_label', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_activities_category'), 'volunteer_activities', ['category'], unique=False)
    op.create_index(op.f('ix_volunteer_activities_id'), 'volunteer_activities', ['id'], unique=False)
    op.create_index(op.f('ix_volunteer_activities_slug'), 'volunteer_activities', ['slug'], unique=True)
    op.create_index(op.f('ix_volunteer_activities_status'), 'volunteer_activities', ['status'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_owner_id'), 'items', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_owner_id'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_volunteer_activities_status'), table_name='volunteer_activities')
    op.drop_index(op.f('ix_volunteer_activities_slug'), table_name='volunteer_activities')
    op.drop_index(op.f('ix_volunteer_activities_id'), table_name='volunteer_activities')
    op.drop_index(op.f('ix_volunteer_activities_category'), table_name='volunteer_activities')
    op.drop_table('volunteer_activities')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_support_opportunities_status'), table_name='support_opportunities')
    op.drop_index(op.f('ix_support_opportunities_slug'), table_name='support_opportunities')
    op.drop_index(op.f('ix_support_opportunities_kind'), table_name='support_opportunities')
    op.drop_index(op.f('ix_support_opportunities_id'), table_name='support_opportunities')
    op.drop_table('support_opportunities')
    op.drop_index(op.f('ix_newsletter_subscribers_id'), table_name='newsletter_subscribers')
    op.drop_index(op.f('ix_newsletter_subscribers_email'), table_name='newsletter_subscribers')
    op.drop_table('newsletter_subscribers')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_session_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_occurred_at'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_name'), table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('ix_analytics_daily_rollups_rollup_date'), table_name='analytics_daily_rollups')
    op.drop_index(op.f('ix_analytics_daily_rollups_metric_key'), table_name='analytics_daily_rollups')
    op.drop_table('analytics_daily_rollups')
    op.drop_index(op.f('ix_admin_volunteer_programs_id'), table_name='admin_volunteer_programs')
    op.drop_table('admin_volunteer_programs')
    op.drop_index(op.f('ix_admin_events_id'), table_name='admin_events')
    op.drop_table('admin_events')
    # ### end Alembic commands ###
