import type { SupportOpportunity } from "@/lib/api";

/** Seeded wishlist items — shown when the API returns no active wishlist needs. */
export const seededWishlistItems: SupportOpportunity[] = [
  {
    id: -1,
    slug: "athlete-training-kits",
    kind: "wishlist",
    title: "Athlete Training Kits",
    description: "Kits give members dependable equipment for practising skills and reaching their next sporting milestone.",
    impact_statement: "HKD 600 funds one reusable training kit for weekly sport sessions.",
    image_url: "https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=900&q=80",
    target_amount_hkd: 12000,
    funded_amount_hkd: 3600,
    moonclerk_url: null,
    purchase_url: null,
    quantity_needed: 20,
    quantity_secured: 6,
    status: "active",
    display_order: 50,
    progress_percent: 30,
    created_at: "",
    updated_at: "",
  },
  {
    id: -2,
    slug: "nutrition-workshop-equipment",
    kind: "wishlist",
    title: "Nutrition Workshop Equipment",
    description: "Practical equipment helps members and families turn nutrition knowledge into confident everyday choices.",
    impact_statement: "HKD 1,500 equips one hands-on nutrition station.",
    image_url: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=900&q=80",
    target_amount_hkd: 18000,
    funded_amount_hkd: 4500,
    moonclerk_url: null,
    purchase_url: null,
    quantity_needed: 12,
    quantity_secured: 3,
    status: "active",
    display_order: 60,
    progress_percent: 25,
    created_at: "",
    updated_at: "",
  },
  {
    id: -3,
    slug: "creative-learning-tablets",
    kind: "wishlist",
    title: "Creative Learning Tablets",
    description: "Shared tablets expand how members communicate, create, learn, and show what they know.",
    impact_statement: "HKD 4,000 funds one shared accessibility-friendly tablet.",
    image_url: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80",
    target_amount_hkd: 24000,
    funded_amount_hkd: 8000,
    moonclerk_url: null,
    purchase_url: null,
    quantity_needed: 6,
    quantity_secured: 2,
    status: "active",
    display_order: 70,
    progress_percent: 33,
    created_at: "",
    updated_at: "",
  },
  {
    id: -4,
    slug: "family-day-transport",
    kind: "wishlist",
    title: "Family Day Transport",
    description: "Accessible transport helps families join community activities without cost becoming the barrier.",
    impact_statement: "HKD 2,000 covers an accessible coach for one family day route.",
    image_url: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=900&q=80",
    target_amount_hkd: 20000,
    funded_amount_hkd: 9200,
    moonclerk_url: null,
    purchase_url: null,
    quantity_needed: 10,
    quantity_secured: 4,
    status: "active",
    display_order: 80,
    progress_percent: 46,
    created_at: "",
    updated_at: "",
  },
  {
    id: -5,
    slug: "art-studio-supplies",
    kind: "wishlist",
    title: "Art Studio Supplies",
    description: "Quality supplies help members explore identity, communication, and confidence through art.",
    impact_statement: "HKD 300 fills one art box for a member-led creative session.",
    image_url: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=900&q=80",
    target_amount_hkd: 9000,
    funded_amount_hkd: 3900,
    moonclerk_url: null,
    purchase_url: null,
    quantity_needed: 30,
    quantity_secured: 13,
    status: "active",
    display_order: 90,
    progress_percent: 43,
    created_at: "",
    updated_at: "",
  },
];
